runtime: nodejs18

env: standard

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 5
  target_cpu_utilization: 0.65

handlers:
  - url: /.*
    secure: always
    script: auto

env_variables:
  NODE_ENV: "production"
